### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by SergioCupido** [MoistCoder/CockyGrabber#14]
i'm so ignorant about these things how do i set it up

**Comment by MoistCoder** [comment]
Download the latest version of CockyGrabber which is 2.1: [link](https://github.com/MoistCoder/CockyGrabber/releases/tag/2.1.0)

After that you will need to add:

- [BouncyCastle](http://www.bouncycastle.org/csharp/)
- [System.Data.SQLite](https://system.data.sqlite.org/)
- [System.Security.Cryptography.ProtectedData](http://www.dot.net/)

to your Project.
They are already included in the binaries.zip file but you can also easily install them with nuget in visual studio.
_(I'm working on custom classes that will replace those packages in the future so that you won't need to add them anymore)_

and then you are basically ready...

Just follow the examples in [the usage documentation](https://github.com/MoistCoder/CockyGrabber/wiki/Usage):
> Grabbing stuff with CockyGrabber is really easy! To set an example here is how to collect Chrome cookies:
```cs
ChromeGrabber grabber = new ChromeGrabber(); // Create Grabber
var cookies = grabber.GetCookies(); // Collect all Cookies with GetCookies()

// Print the Hostname, Name, and Value of every cookie:
foreach(Chromium.Cookie cookie in cookies) // Since Chrome is a Chromium-based Browser it uses Chromium Cookies
{
    string cookieHostname = cookie.HostKey;
    string cookieName = cookie.Name;
    string cookieValue = cookie.EncryptedValue;
    Console.WriteLine($"{cookieHostname}: {cookieName} = {cookieValue}");
}
```

I hope this helps

**Comment by SergioCupido** [comment]
I'm sorry but I seriously don't understand anything please can you make a video of at least 30 seconds on how to do it please

**Comment by rolltidehero** [comment]
> Download the latest version of CockyGrabber which is 2.1: [link](https://github.com/MoistCoder/CockyGrabber/releases/tag/2.1.0)
> 
> After that you will need to add:
> 
> * [BouncyCastle](http://www.bouncycastle.org/csharp/)
> * [System.Data.SQLite](https://system.data.sqlite.org/)
> * [System.Security.Cryptography.ProtectedData](http://www.dot.net/)
> 
> to your Project. They are already included in the binaries.zip file but you can also easily install them with nuget in visual studio. _(I'm working on custom classes that will replace those packages in the future so that you won't need to add them anymore)_
> 
> and then you are basically ready...
> 
> Just follow the examples in [the usage documentation](https://github.com/MoistCoder/CockyGrabber/wiki/Usage):
> 
> > Grabbing stuff with CockyGrabber is really easy! To set an example here is how to collect Chrome cookies:
> 
> ```cs
> ChromeGrabber grabber = new ChromeGrabber(); // Create Grabber
> var cookies = grabber.GetCookies(); // Collect all Cookies with GetCookies()
> 
> // Print the Hostname, Name, and Value of every cookie:
> foreach(Chromium.Cookie cookie in cookies) // Since Chrome is a Chromium-based Browser it uses Chromium Cookies
> {
>     string cookieHostname = cookie.HostKey;
>     string cookieName = cookie.Name;
>     string cookieValue = cookie.EncryptedValue;
>     Console.WriteLine($"{cookieHostname}: {cookieName} = {cookieValue}");
> }
> ```
> 
> I hope this helps

Very helpful. Nice job!
