### ISSUE TITLE
Add exceptions for GeckoNotFound and BlinkNotFound for UniversalGrabber

### ISSUE THREAD

**Issue by DoorsDev** [MoistCoder/CockyGrabber#31]
Title says it all. Just removing the exception of when gecko or blink isnt found can also do the job tho.

**Comment by MoistCoder** [comment]
If I understand correctly, you are referring to the problem that occurs when calling Get()-methods of the UniversalGrabber, that if no data is found from any browser, the program crashes because an exception is thrown: This has been fixed in the latest update ([2.4.0](https://github.com/MoistCoder/CockyGrabber/tree/2.4.0))
